---
title: "Session 5"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
library(dplyr)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF"
)
```

## The pipe operator

- It can be written as %>% or |>

- Makes your code more clear

```{r, eval=FALSE}
mutate(x, y=x+1)
# same as 
x %>% 
  mutate(y=x+1)
# or
x |>
  mutate(y=x+1)

```


---
# Why?

- With the pipe operator we can chain multiple functions together.

- Calculate mean total points grouped by playoffs.
```{r}
df <- readRDS('./nba.rds')

df %>% 
  group_by(Playoff) %>% 
  summarize(avg_pts=mean(PTS))
```

---
## Your turn


